<?php

use Illuminate\Support\Facades\Route;
use App\Livewire\TransactionsTable;
use App\Livewire\TransactionsCreate;
use App\Livewire\StaffActionsTable;
use App\Livewire\PlayersTable;
use App\Http\Livewire\GamesTable;
use App\Http\Middleware\CheckRole;
use App\Http\Controllers\Auth\AuthenticatedSessionController;

// Public routes
Route::view('/', 'welcome');

// Auth-protected routes
Route::middleware(['auth.any', 'verified'])->group(function () {

    // Dashboard
    Route::view('/dashboard', 'dashboard')->name('dashboard');

    // Profile
    Route::view('/profile', 'profile')->name('profile');

});

Route::get('/transactions', function () {
    return view('pages.transactions'); // this points to resources/views/transactions.blade.php
})->middleware(['auth.any', 'verified'])->name('transactions');

Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])
    ->middleware('auth.any')
    ->name('logout');

Route::get('/players', function () {
    return view('players.index'); // we will create this Blade
})->name('players.index');

Route::get('/staffmanagement', function () {
    return view('staffs.index'); // we will create this Blade
})->name('staffs.index');

Route::get('/editprofile', function () {
    return view('admin.editprofile'); // we will create this Blade
})->name('admin.editprofile');

Route::get('/games', function () {
    return view('pages.games'); // Blade file we created
})->name('games');


Route::middleware(['auth', CheckRole::class.':admin'])->group(function () {
    Route::get('/staff', function () {
        return view('staff.index'); // staff management page
    })->name('staff.index');

    // Only main admin can create/edit/delete players & transactions
});



// Auth routes generated by Breeze/Jetstream or your auth scaffolding
require __DIR__.'/auth.php';
