<?php

use Illuminate\Support\Facades\Route;
use App\Livewire\TransactionsTable;
use App\Livewire\TransactionsCreate;
use App\Livewire\StaffActionsTable;
use App\Livewire\PlayersTable;
use App\Http\Livewire\GamesTable;
use App\Http\Middleware\CheckRole;
use App\Http\Controllers\Auth\AuthenticatedSessionController;

// Public routes
Route::view('/', 'welcome');

// Auth-protected routes
Route::middleware(['auth.any', 'verified'])->group(function () {

    // Dashboard
    Route::view('/dashboard', 'pages.dashboard-page')->name('dashboard');

    // Profile
    Route::view('/profile', 'profile')->name('profile');

});

Route::get('/transactions', function () {
    return view('pages.transactions'); // this points to resources/views/transactions.blade.php
})->middleware(['auth.any', 'verified'])->name('transactions');

Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])
    ->middleware('auth.any')
    ->name('logout');

Route::get('/players', function () {
    return view('players.index'); // we will create this Blade
})->middleware(['auth.any', 'verified'])->name('players.index');

Route::get('/staffmanagement', function () {
    return view('staffs.index'); // we will create this Blade
})->middleware(['auth.any', 'verified'])->name('staffs.index');

Route::get('/editprofile', function () {
    return view('admin.editprofile'); // we will create this Blade
})->middleware(['auth.any', 'verified'])->name('admin.editprofile');

Route::get('/games', function () {
    return view('pages.games'); // Blade file we created
})->middleware(['auth.any', 'verified'])->name('games');

Route::get('/wallets', function () {
    return view('pages.wallets'); // Blade file we created
})->middleware(['auth.any', 'verified'])->name('wallets');

Route::get('/wallet-details', function () {
    return view('pages.wallet-details-page'); // Blade file we created
})->middleware(['auth.any', 'verified'])->name('wallet-details');

Route::get('/player-rankings', function () {
    return view('pages.player-rankings-page'); // Blade file we created
})->middleware(['auth.any', 'verified'])->name('player-rankings');

Route::get('/player-leaderboard', function () {
    return view('pages.player-leaderboard-page'); // Blade file we created
})->middleware(['auth.any', 'verified'])->name('player-leaderboard');



Route::get('/game-credits', function() {
    return view('pages.game-credits');
})->middleware(['auth.any','verified'])->name('game-credits');



Route::middleware(['auth', CheckRole::class.':admin'])->group(function () {
    Route::get('/staff', function () {
        return view('staff.index'); // staff management page
    })->name('staff.index');
});



// Auth routes generated by Breeze/Jetstream or your auth scaffolding
require __DIR__.'/auth.php';
