<?php

use Illuminate\Support\Facades\Route;
use App\Livewire\TransactionsTable;
use App\Livewire\TransactionsCreate;
use App\Livewire\StaffActionsTable;
use App\Livewire\PlayersTable;
use App\Http\Livewire\GamesTable;
use App\Http\Middleware\CheckRole;
use App\Http\Middleware\CheckStaffRole; // <-- new middleware
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\HouseReportsPdfController;
use App\Livewire\StaffProfile;
use App\Livewire\ChatApp;

// Public routes
Route::view('/', 'welcome');





// Auth-protected routes for all logged-in users
Route::middleware(['auth.any', 'verified'])->group(function () {

    // Dashboard (everyone can access)
    Route::view('/dashboard', 'pages.dashboard-page')->name('dashboard');

    // Profile (everyone can access)
    Route::view('/profile', 'profile')->name('profile');

    Route::get('/players', fn() => view('players.index'))->name('players.index');
    Route::get('/transactions', fn() => view('pages.transactions'))->name('transactions');
    Route::get('/games', fn() => view('pages.games'))->name('games');
    Route::get('/chat', fn() => view('pages.chat-app-page'))->name('chat');
    Route::middleware('auth:staff')->group(function () {
        ;    Route::get('/staff-profile', fn() => view('pages.staff-profile-page'))->name('staff-profile');
    });
});

// Logout
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])
    ->middleware('auth.any')
    ->name('logout');

// Shared pages accessible by both support_agent & wallet_manager


// Wallet manager exclusive pages
Route::middleware(['auth.any', 'verified', CheckStaffRole::class.':wallet_manager'])->group(function () {
    Route::get('/wallets', fn() => view('pages.wallets'))->name('wallets');
    Route::get('/wallet-details', fn() => view('pages.wallet-details-page'))->name('wallet-details');
    Route::get('/player-rankings', fn() => view('pages.player-rankings-page'))->name('player-rankings');
    Route::get('/player-leaderboard', fn() => view('pages.player-leaderboard-page'))->name('player-leaderboard');
    Route::get('/daily-player-leaderboard', fn() => view('pages.player-leaderboard-daily-page'))->name('daily-player-leaderboard');
    Route::get('/game-performance', fn() => view('pages.game-performance-page'))->name('game-performance');
    Route::get('/game-points', fn() => view('pages.game-points-page'))->name('game-points');
    Route::get('/monthly-wallet-updates', fn() => view('pages.monthly-wallet-updates-page'))->name('monthly-wallet-updates');
    Route::get('/reports', fn() => view('pages.housesupport-reports-page'))->name('reports');

    Route::get('/housesupport-report/pdf', [HouseReportsPdfController::class, 'download'])->name('housesupport-report.pdf');
});

// Admin-only pages
Route::middleware(['auth', CheckRole::class.':admin'])->group(function () {
    Route::get('/staff', fn() => view('staff.index'))->name('staff.index');
    Route::get('/game-credits', fn() => view('pages.game-credits'))->name('game-credits');
    Route::get('/staffmanagement', fn() => view('staffs.index'))->name('staffs.index');
    Route::get('/editprofile', fn() => view('admin.editprofile'))->name('admin.editprofile');
    Route::get('/player-agents', fn() => view('pages.player-agents-page'))->name('player-agents');
    Route::get('/chat-management', fn() => view('pages.chat-management-page'))->name('chat.management');
    Route::get('/game-credits-credentials', fn() => view('pages.game-credits-credentials-page'))
        ->name('game-credits-credentials');
});
/*
|--------------------------------------------------------------------------
| Remaining routes (accessible to admin or wallet manager)
|--------------------------------------------------------------------------
*/
Route::middleware(['auth.any', 'verified', CheckStaffRole::class.':wallet_manager'])->group(function () {
    Route::get('/housesupport-report/pdf', [HouseReportsPdfController::class, 'download'])
        ->name('housesupport-report.pdf');
});

// Auth routes generated by Breeze/Jetstream or your auth scaffolding
require __DIR__.'/auth.php';
